# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-28 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.CharField(blank=True, max_length=300, null=True)),
                ('formula', models.CharField(blank=True, max_length=300, null=True)),
                ('crystal_system', models.CharField(blank=True, max_length=300, null=True)),
                ('unit_cell', models.CharField(blank=True, max_length=300, null=True)),
                ('color', models.CharField(blank=True, max_length=300, null=True)),
                ('cleavage', models.CharField(blank=True, max_length=300, null=True)),
                ('crystal_symmetry', models.CharField(blank=True, max_length=300, null=True)),
                ('mohs_scale', models.CharField(blank=True, max_length=300, null=True)),
                ('image_caption', models.CharField(blank=True, max_length=300, null=True)),
                ('image_filename', models.CharField(blank=True, max_length=300, null=True)),
                ('strunz_classification', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
